Repository DHKH-null29/linky_way_front, pull requests merged in 2022-05, with the labels that each got.

#13 버튼 컴포넌트 추가하기
  src/components/Buttons.js
Labels: ⭐ Feature, ✨Suggestion, 🐣GUK

#16 아이콘 컴포넌트 추가
  package-lock.json
  package.json
  src/components/icons/AnimatedIcon.js
  src/components/icons/CheckMark.js
  src/components/icons/CommonInput.js
  src/components/icons/Email.js
  src/components/icons/Password.js
  src/components/icons/WarningAlert.js
  src/styles/colors.js
  src/styles/icons.js
  src/styles/index.js
Labels: 🎃 DONG

#18 아이콘이 곁들여진 인풋 컴포넌트 추가
  src/components/IconInput.js
Labels: 🎃 DONG

#25 회원 가입 페이지 구현
  src/pages/JoinPage.js
  src/styles/shadow.js
Labels: ⭐ Feature, 🎃 DONG

#23 로그인 페이지 구현
  src/pages/LoginPage.js
Labels: ⭐ Feature, 😱 Help, 🐣GUK

#35 버튼 관련 문제 해결하기
  src/components/Buttons.js
  src/components/IconInput.js
Labels: 🎃 DONG, 🐣GUK
